mamrh_Acceuil:
    pattern:  /Acceuil
    defaults: { _controller: MAMRHBundle:RH:Acceuil }

mamrh_AjoutProjet:
    pattern:  /AjoutProjet
    defaults: { _controller: MAMRHBundle:Projet:AjoutProjet }

mamrh_AjoutSuivi:
    pattern:  /AjoutSuivi/{id}
    defaults: { _controller: MAMRHBundle:Projet:AjoutSuivi }

mamrh_VoirProfil:
    pattern:  /VoirProfil/{id}
    defaults: { _controller: MAMRHBundle:Projet:VoirProfil }

mamrh_ModifiProfil:
    pattern:  /ModifiProfil/{id}
    defaults: { _controller: MAMRHBundle:Projet:ModifiProfil }

mamrh_ListeProjet:
    pattern:  /ListeProjet
    defaults: { _controller: MAMRHBundle:Projet:ListeProjet }

mamrh_ajoutemploye:
    path:    /ajoutemploye
    defaults: {_controller: MAMRHBundle:RH:ajoutemploye}

mamrh_ajoutoffre:
    path:    /AjoutOffre
    defaults: {_controller: MAMRHBundle:RH:ajoutoffre}

mamrh_demande:
     path:    /Demande
     defaults: {_controller: MAMRHBundle:Employe:demande}

mamrh_ajoutstagiaire:
    path:    /AjoutStagiaire
    defaults: {_controller: MAMRHBundle:RH:ajoutstagiaire}

mamrh_affichemp:
    path:    /AffichEmp
    defaults: {_controller: MAMRHBundle:RH:getemployenormal}

mamrh_affichstag:
    path:    /AfficheStag
    defaults: {_controller: MAMRHBundle:RH:getstagiaire}

mamrh_rh_demande:
     path:    /listdemande
     defaults: {_controller: MAMRHBundle:RH:demande}

mamrh_rh_validdemande:
     path:    /validdemande/{id}
     defaults: {_controller: MAMRHBundle:RH:validdemande}

mamrh_ListSuivi:
    pattern:  /Suivi/{id}
    defaults: { _controller: MAMRHBundle:Projet:Listsuivi }
