mam_site:
    resource: "@MAMSiteBundle/Resources/config/routing.yml"
    prefix:   /

mamrh:
    resource: "@MAMRHBundle/Resources/config/routing.yml"
    prefix:   /app

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"