security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CHEF_PROJET:       ROLE_EMP
        ROLE_SUPER_ADMIN:       [ROLE_CHEF_DEP,ROLE_EMP,ROLE_CHEF_PROJET,ROLE_RH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main_login:
            pattern:   ^/login
            anonymous: true

        main:
            pattern: ^/
            anonymous:    false
            provider: fos_userbundle
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_provider: form.csrf_provider
                default_target_path: /app/ajoutemploye
            logout:
                path:   logout
                target: /login
            remember_me:
                 key:     %secret%

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }


