<?php

namespace MAM\RHBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends EntityRepository
{
    public function condidatoffre($id){
        $nbrdemande = $this->createQueryBuilder('c')
            ->leftJoin('c.offres','o')
            ->where('o.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
        return $nbrdemande;
    }
}
