<?php

namespace MAM\RHBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChefProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefProjetRepository extends EntityRepository
{
}
