<?php

namespace MAM\RHBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeRepository extends EntityRepository
{
    public function getemployenormal()
    {

        $query = $this->createQueryBuilder('e')
            ->where('e.Bye = :f')
            ->setParameter('f',false)
            ->getQuery();
        $e=$query-> getresult();
        return $e;
    }
}
