<?php

namespace MAM\RHBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL;

/**
 * EmployenormalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployenormalRepository extends EntityRepository
{
    public function updatediscrim($from,$to)
    {
        $query = $this->_em->createQuery("UPDATE employe SET dtype=" . $to . " WHERE id=" . $from->getId());
        return $query->getResult();
    }

    public function getemployenormal()
    {

        $query = $this->createQueryBuilder('e')
            ->where('e.Bye = :f')
            ->setParameter('f',false)
            ->getQuery();
        $e=$query-> getresult();
        return $e;
    }
}
