<?php

namespace MAM\RHBundle\Entity;

use DateTime;
use Doctrine\ORM\EntityRepository;
use MAM\UserBundle\Entity\User;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository
{

    public function getnbrprojet(User $user){
        $nbrproj = $this->createQueryBuilder('d')
            ->select('COUNT(DISTINCT d.id)')
            ->where('d.Date_fin < :d')
            ->leftJoin('d.employeNormals','e')
            ->leftJoin('e.user','u')
            ->andwhere('u.id = :user')
            ->setParameter('d', new Datetime())
            ->setParameter('user', $user->getId())
            ->getQuery()
            ->getResult();
        return $nbrproj;
    }

    public function getprojetdep(User $user){
        $projets = $this->createQueryBuilder('p')
            ->leftJoin('p.chefDepartement','c')
            ->addSelect('c')
            ->where('c.user = :u')
            ->setParameter('u', $user)
            ->getQuery()
            ->getResult();

        return $projets;
    }
}
