<?php

namespace MAM\RHBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StagiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StagiaireRepository extends EntityRepository
{
    public function getstagiaire()
    {

        $query = $this->createQueryBuilder('s')
            ->getQuery();
        $s=$query-> getresult();
        return $s;
    }
}
