<?php

namespace MAM\RHBundle\Entity;

use DateTime;
use Doctrine\ORM\EntityRepository;
use MAM\UserBundle\Entity\User;

/**
 * StagiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StagiaireRepository extends EntityRepository
{
    public function getstagiaire(User $user)
    {

        $query = $this->createQueryBuilder('s')
            ->where('s.date_fin >= :df')
            ->leftJoin('s.employeNormal','e')
            ->leftJoin('e.user','u')
            ->andwhere('u.id = :user')
            ->setParameter('df', new Datetime)
            ->setParameter('user', $user->getId())
            ->getQuery();
        $s=$query-> getresult();
        return $s;
    }

    public function getstagiairerh()
    {

        $query = $this->createQueryBuilder('s')
            ->where('s.date_fin >= :df')
            ->setParameter('df', new Datetime)
            ->getQuery();
        $s=$query-> getresult();
        return $s;
    }

    public function archivestagiaire()
    {

        $query = $this->createQueryBuilder('s')
            ->where('s.date_fin < :df')
            ->setParameter('df', new Datetime())
            ->getQuery();
//var_dump(new Datetime());
        $s=$query-> getresult();
        return $s;
    }

    public function getstagiaireid($id)
    {

        $query = $this->createQueryBuilder('s')
            ->where('s.id = :id')
            ->setParameter('id',$id)
            ->getQuery();
        $s=$query-> getresult();
        return $s;
    }

    public function getnbrprojet(User $user){
        $nbrstag = $this->createQueryBuilder('d')
            ->select('COUNT(DISTINCT d.id)')
            ->where('d.date_fin >= :d')
            ->setParameter('d', new Datetime())
            ->leftJoin('d.employeNormal','e')
            ->leftJoin('e.user','u')
            ->andwhere('u.id = :user')
            ->setParameter('user', $user->getId())
            ->getQuery()
            ->getResult();
        return $nbrstag;
    }

    public function getnbrprojetrh(){
        $nbrstag = $this->createQueryBuilder('d')
            ->select('COUNT(DISTINCT d.id)')
            ->where('d.date_fin >= :d')
            ->setParameter('d', new Datetime())
            ->getQuery()
            ->getResult();
        return $nbrstag;
    }
}
