<?php

namespace MAM\RHBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuiviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviRepository extends EntityRepository
{
    public function getsuivis($id){

        $suivis = $this->createQueryBuilder('s')
            // On joint sur l'attribut image
            ->leftJoin('s.projet', 'p')
            ->addSelect('p')
            // On joint sur l'attribut categories
            ->where('p.id = :proj')
            ->setParameter('proj', $id)
            ->getQuery()
            ->getResult();

        return $suivis;
    }
}
